apiVersion: v1
kind: Service
metadata:
  name: cpu-stress-test
  namespace: stress-test
  labels:
    app: cpu-stress-test
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cpu-stress-test